"""Internal contracts for normalized stock data providers."""

from .contracts import (
    Capability,
    FundamentalDataProvider,
    FundamentalSnapshot,
    MarketDataProvider,
    MarketSnapshot,
    PriceUnit,
    ProviderSource,
    ReferenceDataProvider,
    ReferenceSnapshot,
    SOURCE_OWNERSHIP_BY_CAPABILITY,
    ShareCount,
    ShareType,
    SnapshotMetadata,
    SourceOwnership,
    ValuationDataProvider,
    ValuationSnapshot,
    cover_source,
    main_source,
    owns_capability,
)
from .store import SnapshotRead, SnapshotStore
from .vnstock_provider import (
    RequestPacer,
    VnstockFundamentalProvider,
    VnstockProviderError,
    VnstockReadFailed,
    VnstockReferenceProvider,
    quota_per_minute,
)

__all__ = [
    "Capability",
    "FundamentalDataProvider",
    "FundamentalSnapshot",
    "MarketDataProvider",
    "MarketSnapshot",
    "PriceUnit",
    "ProviderSource",
    "ReferenceDataProvider",
    "ReferenceSnapshot",
    "RequestPacer",
    "SOURCE_OWNERSHIP_BY_CAPABILITY",
    "ShareCount",
    "ShareType",
    "SnapshotMetadata",
    "SnapshotRead",
    "SnapshotStore",
    "SourceOwnership",
    "ValuationDataProvider",
    "ValuationSnapshot",
    "VnstockFundamentalProvider",
    "VnstockProviderError",
    "VnstockReadFailed",
    "VnstockReferenceProvider",
    "cover_source",
    "main_source",
    "owns_capability",
    "quota_per_minute",
]
