"""Internal contracts for normalized stock data providers.

Snapshot store and adapters (vnstock, FiinQuant, DNSE, CafeF) were dropped when
the market surfaces were ripped out. Only the source-neutral contract types
survive, because the agent tool ``price_check`` reads ``PriceBasis`` and
``SessionSnapshot`` off this package by name.
"""

from .contracts import (
    BatchTooLarge,
    Capability,
    CorporateActionEvent,
    CorporateActionProvider,
    Exchange,
    MARKET_SCHEMA_VERSION,
    FundamentalDataProvider,
    FundamentalSnapshot,
    ListingEntry,
    ListingRosterProvider,
    MarketDataProvider,
    MarketHistoryProvider,
    MarketIndexHistoryProvider,
    MarketIndexSnapshot,
    MarketSnapshot,
    PriceBasis,
    PriceUnit,
    ProviderSource,
    RANKED_EXCHANGES,
    ReferenceDataProvider,
    ReferenceSnapshot,
    SOURCE_OWNERSHIP_BY_CAPABILITY,
    SessionSnapshot,
    ShareCount,
    ShareType,
    SnapshotMetadata,
    SourceOwnership,
    SymbolSnapshot,
    ValuationDataProvider,
    ValuationSnapshot,
    cover_source,
    main_source,
    owns_capability,
)

__all__ = [
    "BatchTooLarge",
    "Capability",
    "CorporateActionEvent",
    "CorporateActionProvider",
    "Exchange",
    "MARKET_SCHEMA_VERSION",
    "FundamentalDataProvider",
    "FundamentalSnapshot",
    "ListingEntry",
    "ListingRosterProvider",
    "MarketDataProvider",
    "MarketHistoryProvider",
    "MarketIndexHistoryProvider",
    "MarketIndexSnapshot",
    "MarketSnapshot",
    "PriceBasis",
    "PriceUnit",
    "ProviderSource",
    "RANKED_EXCHANGES",
    "ReferenceDataProvider",
    "ReferenceSnapshot",
    "SOURCE_OWNERSHIP_BY_CAPABILITY",
    "SessionSnapshot",
    "ShareCount",
    "ShareType",
    "SnapshotMetadata",
    "SourceOwnership",
    "SymbolSnapshot",
    "ValuationDataProvider",
    "ValuationSnapshot",
    "cover_source",
    "main_source",
    "owns_capability",
]
