// @vitest-environment jsdom
/**
 * The panel, against the artifact the server actually sends.
 *
 * The fixture is a real Study run regenerated by `make contracts`, so what is
 * rendered here is the payload the wire carries rather than a sample written to
 * suit the components. Three claims are worth a test:
 *
 * *The skeleton is the right height before anything arrives.* The announcement
 * says how many blocks there are, and a panel that opened empty and then jumped
 * would be worse than one that opened slowly.
 *
 * *A re-opened Thread shows the day the answer was written about.* `asOf` is
 * frozen when the Study runs, and a picture with no date on it reads as now.
 *
 * *A block nothing can draw is still a block.* It degrades to a table and says
 * so, in place, because a dropped block is a hole the reader cannot see.
 */

import { QueryClient, QueryClientProvider } from "@tanstack/react-query"
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react"
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest"

import fixture from "../../../../../contracts/fixtures/artifact-intraday-liquidity.json"
import { AlphaRefusalError } from "@/lib/alpha"
import type { ArtifactPayload } from "@/lib/alpha-desk/types"

const fetchArtifact = vi.fn()
vi.mock("@/lib/alpha-desk/api", () => ({
  fetchArtifact: (id: string) => fetchArtifact(id),
}))

const { SignalDeskPanel } = await import("./signal-desk-panel")

const ARTIFACT_ID = "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"

function payload(overrides: Partial<ArtifactPayload> = {}): ArtifactPayload {
  return {
    id: ARTIFACT_ID,
    study_name: fixture.studyName,
    study_version: fixture.studyVersion,
    params: fixture.params,
    signal_desk_spec: fixture.signal_deskSpec,
    frames: fixture.frames,
    provenance: fixture.provenance,
    created_at: "2026-08-21T09:00:00+00:00",
    ...overrides,
  } as ArtifactPayload
}

function draw(node: React.ReactElement) {
  const client = new QueryClient({
    defaultOptions: { queries: { retry: false, gcTime: Infinity } },
  })
  return render(<QueryClientProvider client={client}>{node}</QueryClientProvider>)
}

beforeEach(() => {
  fetchArtifact.mockReset()
  // ResizeObserver is what recharts measures its container with, and jsdom has
  // none. A stub that reports nothing is enough: the assertions here are about
  // what is on the page, not about chart geometry.
  vi.stubGlobal(
    "ResizeObserver",
    class {
      observe() {}
      unobserve() {}
      disconnect() {}
    },
  )
})

afterEach(() => {
  cleanup()
  vi.unstubAllGlobals()
})

describe("before the numbers arrive", () => {
  it("holds one skeleton per announced block, so the panel does not jump", () => {
    fetchArtifact.mockReturnValue(new Promise(() => {}))

    const { container } = draw(
      <SignalDeskPanel artifactId={ARTIFACT_ID} title="Thanh khoản STB" blockCount={4} />,
    )

    expect(container.querySelectorAll(".animate-pulse")).toHaveLength(4)
    expect(screen.getByText("Thanh khoản STB")).toBeInTheDocument()
  })

  it("says so plainly when the conversation has drawn nothing", () => {
    draw(<SignalDeskPanel artifactId={null} />)

    expect(screen.getByText(/Chưa có Signal Desk nào/)).toBeInTheDocument()
    expect(fetchArtifact).not.toHaveBeenCalled()
  })
})

describe("once the artifact is fetched", () => {
  it("renders every block of the board the server sent", async () => {
    fetchArtifact.mockResolvedValue(payload())

    const spec = fixture.signal_deskSpec
    const visuals = spec.sections.reduce(
      (total, section) =>
        total + section.blocks.filter((block) => block.kind === "visual").length,
      spec.appendix ? 1 : 0,
    )
    const drawn = spec.sections.reduce(
      (total, section) => total + section.blocks.length,
      spec.appendix ? 1 : 0,
    )
    const { container } = draw(
      <SignalDeskPanel artifactId={ARTIFACT_ID} blockCount={drawn} />,
    )

    await waitFor(() =>
      expect(screen.getByText(spec.title)).toBeInTheDocument(),
    )
    // A `section` per board section and a `section` per picture inside it, so a
    // board that quietly dropped a figure lands short here.
    expect(container.querySelectorAll("section")).toHaveLength(
      spec.sections.length + visuals,
    )
    // The strip answers the question and the pictures are the reason to believe
    // it, so a board that drew one and not the other would still pass above.
    expect(screen.getAllByText(spec.kpis[0].label)).not.toHaveLength(0)
    // The heatmap is the hero picture, and it is SVG this build draws itself.
    expect(container.querySelector("svg")).not.toBeNull()
  })

  it("shows the day the numbers were frozen, and how old that is", async () => {
    fetchArtifact.mockResolvedValue(payload())

    const { container } = draw(<SignalDeskPanel artifactId={ARTIFACT_ID} />)

    const sessions = await screen.findByText(
      `${fixture.provenance.sessionsUsed} phiên`,
    )
    const line = sessions.parentElement as HTMLElement
    // The fixture's as-of is pinned in the past, so the age has to be said.
    expect(line.textContent).toMatch(/ngày trước/)
    // And the provider is not named: the strip is a caption for a reader.
    expect(container.textContent).not.toContain("vnstock")
  })

  it("re-opens on the stored as-of rather than asking for a fresher slice", async () => {
    fetchArtifact.mockResolvedValue(payload())

    const sessions = `${fixture.provenance.sessionsUsed} phiên`
    const { unmount } = draw(<SignalDeskPanel artifactId={ARTIFACT_ID} />)
    await screen.findByText(sessions)
    unmount()
    draw(<SignalDeskPanel artifactId={ARTIFACT_ID} />)
    const reopened = await screen.findByText(sessions)

    expect(reopened.parentElement?.textContent).toMatch(/dữ liệu \d{2}\/\d{2}\/\d{4}/)
    // A second mount is a second query client here, so the fetch happening
    // twice is expected; what must not happen is the *content* moving.
    expect(fetchArtifact).toHaveBeenCalledWith(ARTIFACT_ID)
  })

  it("draws a block it cannot render as a table and says which", async () => {
    fetchArtifact.mockResolvedValue(
      payload({
        // A version-one spec on purpose: rows written before the board grammar
        // existed are still on disk and still have to open.
        signal_desk_spec: {
          specVersion: 1,
          title: "Một khối lạ",
          blocks: [
            {
              widget: "session_heatmap",
              widgetVersion: 99,
              frame: Object.keys(fixture.frames)[0],
              options: {},
            },
          ],
        },
      }),
    )

    draw(<SignalDeskPanel artifactId={ARTIFACT_ID} />)

    expect(await screen.findByText(/Hiển thị dạng bảng/)).toBeInTheDocument()
    expect(screen.getByRole("table")).toBeInTheDocument()
  })

  it("says a desk view could not be opened rather than showing an empty panel", async () => {
    // The settled failure, and the one this route was built expecting: the row
    // belongs to another Thread and will belong to it on every later request.
    fetchArtifact.mockRejectedValue(new AlphaRefusalError(404, null, "not found"))

    draw(<SignalDeskPanel artifactId={ARTIFACT_ID} />)

    expect(await screen.findByText(/Không mở được bảng này/)).toBeInTheDocument()
    // No button, because there is nothing a second request would change.
    expect(screen.queryByRole("button", { name: "Thử lại" })).not.toBeInTheDocument()
  })

  it("offers a retry when the fetch failed rather than the artifact being refused", async () => {
    // A dropped connection reaches `alphaFetch` as a bare `TypeError`, never as
    // a refusal carrying a status. The artifact is frozen server-side, so the
    // same request is the whole fix — which is why this one gets a button and
    // the 404 above does not.
    fetchArtifact.mockRejectedValue(new TypeError("Failed to fetch"))

    draw(<SignalDeskPanel artifactId={ARTIFACT_ID} />)

    // The words are the product's shared ones for a dropped connection, not a
    // sentence this panel keeps to itself.
    expect(await screen.findByText(/mạng của bạn đã ngắt/)).toBeInTheDocument()

    fetchArtifact.mockResolvedValue(payload())
    fireEvent.click(screen.getByRole("button", { name: "Thử lại" }))

    // The heading only exists once there is an artifact: the error branch
    // returns before it. Its arrival is the retry having actually landed.
    expect(await screen.findByRole("heading", { level: 3 })).toBeInTheDocument()
    expect(screen.queryByText(/mạng của bạn đã ngắt/)).not.toBeInTheDocument()
  })

  it("says a run drew nothing rather than leaving the panel headless", async () => {
    // Fetched, frozen, and carrying no block. Without a sentence this is the
    // one state indistinguishable from a skeleton that never resolved.
    fetchArtifact.mockResolvedValue(
      payload({ signal_desk_spec: { title: "Không có khối", blocks: [] } }),
    )

    draw(<SignalDeskPanel artifactId={ARTIFACT_ID} />)

    expect(await screen.findByText(/không dựng được khối nào/)).toBeInTheDocument()
  })
})
