/**
 * The Alpha Desk conversation, over the same-origin proxy.
 *
 * Same-origin against the Next route handler rather than FastAPI directly,
 * because the session lives in httpOnly cookies the browser cannot read. That
 * is also why this does not reuse `fetchApi` from `@/lib/api`: those routes are
 * public market data on the API's own origin, and these carry a user.
 *
 * `fetchApi` stays unchanged, deliberately — retro-fitting auth onto the app's
 * twenty-five existing hooks is its own effort (ADR-0013).
 *
 * The request itself is `alphaFetch` from `@/lib/alpha`: the rail and the
 * conversation are the same origin, the same session and the same refusal body,
 * so they read it once. What is here is the conversation's own paths and the
 * shape each one sends.
 *
 * **Admission outcomes arrive here, not in the stream.** A `429` or a `503`
 * from the create call is an ordinary HTTP failure carrying its stable reason,
 * and the caller reads it from the thrown refusal rather than waiting for an
 * event that is never coming.
 */

import { alphaFetch, alphaSend } from "@/lib/alpha"

import type {
  ArtifactPayload,
  CreatedTurn,
  FlagReason,
  MessageFlag,
  MessageHelpful,
  Thread,
  ThreadDetail,
  Turn,
  Usage,
} from "./types"

const BASE = "/api/alpha-desk"

/** Open a Thread. Free-roaming: it is not opened against a symbol. */
export function createThread(title?: string | null): Promise<Thread> {
  return alphaFetch<Thread>("/threads", {
    method: "POST",
    body: JSON.stringify({ title: title ?? null }),
  })
}

/** This user's Threads, most recently touched first. Secondary retrieval only. */
export function listThreads(): Promise<{ threads: Thread[] }> {
  return alphaFetch<{ threads: Thread[] }>("/threads")
}

/** One Thread and its canonical transcript. */
export function fetchThread(threadId: string): Promise<ThreadDetail> {
  return alphaFetch<ThreadDetail>(`/threads/${encodeURIComponent(threadId)}`)
}

/**
 * Rename a Thread, pin it, or both — what the sidebar's per-Thread menu writes.
 *
 * Only the keys present are sent, and that is load bearing on the wire: the
 * backend reads *which fields arrived* rather than their values, so a pin that
 * also carried `title: null` would clear the name it never meant to touch.
 */
export function updateThread(
  threadId: string,
  patch: { title?: string | null; pinned?: boolean },
): Promise<Thread> {
  return alphaFetch<Thread>(`/threads/${encodeURIComponent(threadId)}`, {
    method: "PATCH",
    body: JSON.stringify(patch),
  })
}

/**
 * Delete a Thread and its transcript.
 *
 * Not reversible and not archived: it takes the messages, the traces and the
 * Turns with it. The surface asks before calling this.
 */
export function deleteThread(threadId: string): Promise<void> {
  return alphaSend(`/threads/${encodeURIComponent(threadId)}`, { method: "DELETE" })
}

export interface CreateTurnInput {
  threadId: string
  /** Chosen by the browser before the request. It is the idempotency key. */
  turnId: string
  text: string
  symbols?: string[]
  activeSymbol?: string | null
  retryOfTurnId?: string | null
}

/**
 * Admit and create a Turn.
 *
 * The id is generated by the caller and sent, rather than assigned by the
 * server and returned. That is what makes a retried admission safe on a flaky
 * network: the same id with the same payload resolves to the Turn that already
 * exists instead of starting a second one.
 */
export function createTurn(input: CreateTurnInput): Promise<CreatedTurn> {
  return alphaFetch<CreatedTurn>(`/threads/${encodeURIComponent(input.threadId)}/turns`, {
    method: "POST",
    body: JSON.stringify({
      turn_id: input.turnId,
      text: input.text,
      symbols: input.symbols ?? [],
      active_symbol: input.activeSymbol ?? null,
      retry_of_turn_id: input.retryOfTurnId ?? null,
    }),
  })
}

/**
 * The numbers behind one deskView.
 *
 * A separate request from the transcript, deliberately: a heatmap is thousands
 * of cells and a conversation scrolls, so the text loads at text weight and the
 * picture is fetched by whoever opens the panel.
 *
 * The row is immutable, so the answer may be cached for as long as the tab
 * lives. Re-opening a Thread renders what was frozen; nothing here ever asks
 * the store for a fresher slice.
 */
export function fetchArtifact(artifactId: string): Promise<ArtifactPayload> {
  return alphaFetch<ArtifactPayload>(`/artifacts/${encodeURIComponent(artifactId)}`)
}

/** Idempotent. A second cancel returns the same answer and dispatches nothing. */
export function cancelTurn(turnId: string): Promise<Turn> {
  return alphaFetch<Turn>(`/turns/${encodeURIComponent(turnId)}/cancel`, { method: "POST" })
}

/** One Turn's current state, for a caller that has not opened a stream. */
export function fetchTurn(turnId: string): Promise<Turn> {
  return alphaFetch<Turn>(`/turns/${encodeURIComponent(turnId)}`)
}

/**
 * Flag one assistant message with one reason.
 *
 * Idempotent per message: a second call replaces the reason rather than adding
 * a second flag, because the backend writes a pair of columns and not a row in
 * a table it does not have (`docs/adr/0016`).
 *
 * **It opens nothing.** There is no ticket id in the answer to render, and the
 * surface must not invent one — the response carries the flag and nothing else.
 */
export function flagMessage(messageId: number, reason: FlagReason): Promise<MessageFlag> {
  return alphaFetch<MessageFlag>(`/messages/${messageId}/flag`, {
    method: "POST",
    body: JSON.stringify({ reason }),
  })
}

/** Clear the flag. Both columns, never one of them. */
export function unflagMessage(messageId: number): Promise<MessageFlag> {
  return alphaFetch<MessageFlag>(`/messages/${messageId}/flag`, { method: "DELETE" })
}

/**
 * Mark one assistant message helpful.
 *
 * No body, because the mark carries no reason — the asymmetry with the flag is
 * the point of it. Idempotent per message: a second call answers with the
 * existing stamp rather than moving it.
 */
export function markHelpful(messageId: number): Promise<MessageHelpful> {
  return alphaFetch<MessageHelpful>(`/messages/${messageId}/helpful`, {
    method: "POST",
  })
}

/** Take the mark back, answering with the cleared stamp. */
export function clearHelpful(messageId: number): Promise<MessageHelpful> {
  return alphaFetch<MessageHelpful>(`/messages/${messageId}/helpful`, {
    method: "DELETE",
  })
}

/** Where the browser's `EventSource` points. Same origin, so cookies travel. */
export function turnStreamUrl(turnId: string): string {
  return `${BASE}/turns/${encodeURIComponent(turnId)}/events`
}

/**
 * A fresh Turn id.
 *
 * `crypto.randomUUID` needs a secure context, which localhost and https both
 * are; the fallback exists for the one place that is neither, and it only has
 * to be unique per user rather than unguessable — the backend scopes the id to
 * its owner, so a collision with a stranger's Turn is not reachable.
 */
export function newTurnId(): string {
  if (typeof globalThis.crypto?.randomUUID === "function") {
    return globalThis.crypto.randomUUID()
  }
  return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, (char) => {
    const random = (Math.random() * 16) | 0
    const value = char === "x" ? random : (random & 0x3) | 0x8
    return value.toString(16)
  })
}

/**
 * This account's allowance and what has gone against it.
 *
 * Takes no parameters on purpose: the user is resolved from the session
 * upstream, so there is no shape of this call that reads another account.
 *
 * The numbers move as Turns run, and the daily figures stop being true at
 * Vietnamese midnight — so the caller refetches rather than caching this for
 * the life of the tab.
 */
export function fetchUsage(): Promise<Usage> {
  return alphaFetch<Usage>("/usage")
}
