/**
 * The Alpha Desk conversation, over the same-origin proxy.
 *
 * Same-origin against the Next route handler rather than FastAPI directly,
 * because the session lives in httpOnly cookies the browser cannot read.
 *
 * The request itself is `alphaFetch` from `@/lib/alpha`: the rail and the
 * conversation share one origin, session and refusal body. What is here is the
 * conversation's own paths and the shape each one sends.
 *
 * **Admission outcomes arrive here, not in the stream.** A `429` or a `503`
 * from the create call is an ordinary HTTP failure carrying its stable reason,
 * and the caller reads it from the thrown refusal rather than waiting for an
 * event that is never coming.
 */

import { alphaFetch, alphaSend } from "@/lib/alpha"

import type {
  Attachment,
  Capabilities,
  CreatedTurn,
  FlagReason,
  MessageFlag,
  MessageHelpful,
  ResolvedQuestion,
  Thread,
  ThreadDetail,
  Turn,
  Usage,
} from "./types"

const BASE = "/api/alpha-desk"

/** Open a Thread. Free-roaming: it is not opened against a symbol. */
export function createThread(title?: string | null): Promise<Thread> {
  return alphaFetch<Thread>("/threads", {
    method: "POST",
    body: JSON.stringify({ title: title ?? null }),
  })
}

/** This user's Threads, most recently touched first. Secondary retrieval only. */
export function listThreads(): Promise<{ threads: Thread[] }> {
  return alphaFetch<{ threads: Thread[] }>("/threads")
}

/** One Thread and its canonical transcript. */
export function fetchThread(threadId: string): Promise<ThreadDetail> {
  return alphaFetch<ThreadDetail>(`/threads/${encodeURIComponent(threadId)}`)
}

/**
 * Rename a Thread, pin it, or both — what the sidebar's per-Thread menu writes.
 *
 * Only the keys present are sent, and that is load bearing on the wire: the
 * backend reads *which fields arrived* rather than their values, so a pin that
 * also carried `title: null` would clear the name it never meant to touch.
 */
export function updateThread(
  threadId: string,
  patch: { title?: string | null; pinned?: boolean },
): Promise<Thread> {
  return alphaFetch<Thread>(`/threads/${encodeURIComponent(threadId)}`, {
    method: "PATCH",
    body: JSON.stringify(patch),
  })
}

/**
 * Delete a Thread and its transcript.
 *
 * Not reversible and not archived: it takes the messages, the traces and the
 * Turns with it. The surface asks before calling this.
 */
export function deleteThread(threadId: string): Promise<void> {
  return alphaSend(`/threads/${encodeURIComponent(threadId)}`, { method: "DELETE" })
}

export interface CreateTurnInput {
  threadId: string
  /** Chosen by the browser before the request. It is the idempotency key. */
  turnId: string
  text: string
  symbols?: string[]
  /**
   * Whether the reader threw the Signal Desk switch for this question.
   *
   * Read by the surface and not sent: `CreateTurnRequest` forbids fields it does
   * not declare and it declares no mode, so a body carrying one fails the Turn
   * with a 422 — every Turn, since the switch is off as explicitly as it is on.
   * It stays on the input because the callers already know the answer, and the
   * line that puts it on the wire belongs where it would be translated rather
   * than rediscovered.
   */
  signalDesk?: boolean
  /**
   * The attachments this question carries, by id, in the order they were added.
   *
   * Ids and not files: the bytes went up before the reader finished typing, so
   * this request stays small and stays idempotent. It is part of the payload the
   * backend compares, so the same id with two different pictures is a conflict
   * rather than a silent reuse.
   */
  attachments?: string[]
  retryOfTurnId?: string | null
}

/**
 * Admit and create a Turn.
 *
 * The id is generated by the caller and sent, rather than assigned by the
 * server and returned. That is what makes a retried admission safe on a flaky
 * network: the same id with the same payload resolves to the Turn that already
 * exists instead of starting a second one.
 *
 */
export function createTurn(input: CreateTurnInput): Promise<CreatedTurn> {
  return alphaFetch<CreatedTurn>(`/threads/${encodeURIComponent(input.threadId)}/turns`, {
    method: "POST",
    body: JSON.stringify({
      turn_id: input.turnId,
      text: input.text,
      symbols: input.symbols ?? [],
      attachments: input.attachments ?? [],
      retry_of_turn_id: input.retryOfTurnId ?? null,
    }),
  })
}

/**
 * Put one file up and get its id back.
 *
 * Sent when the file is chosen, not when Send is pressed. The reader watches the
 * progress while they are still writing, and the Turn itself then carries a
 * short list of ids — which is what keeps `createTurn` fast and keeps its
 * idempotency key comparable.
 *
 * `FormData` on purpose, and with no `Content-Type` of its own: the browser
 * computes the multipart boundary from the body at send time, and `sendAlpha`
 * knows to leave the header alone for exactly this case.
 */
export function uploadAttachment(file: File): Promise<Attachment> {
  const body = new FormData()
  body.append("file", file)
  return alphaFetch<Attachment>("/attachments", { method: "POST", body })
}

/**
 * Where the bytes of one attachment live.
 *
 * A URL rather than a fetch, because the consumers are an `<img src>` and a
 * link: handing them a string lets the browser do its own caching, and the row
 * is immutable so that cache is correct for as long as the tab lives.
 */
export function attachmentUrl(attachmentId: string): string {
  return `/api/alpha-desk/attachments/${encodeURIComponent(attachmentId)}`
}

/** Idempotent. A second cancel returns the same answer and dispatches nothing. */
export function cancelTurn(turnId: string): Promise<Turn> {
  return alphaFetch<Turn>(`/turns/${encodeURIComponent(turnId)}/cancel`, { method: "POST" })
}

/** One Turn's current state, for a caller that has not opened a stream. */
export function fetchTurn(turnId: string): Promise<Turn> {
  return alphaFetch<Turn>(`/turns/${encodeURIComponent(turnId)}`)
}

/**
 * Flag one assistant message with one reason.
 *
 * Idempotent per message: a second call replaces the reason rather than adding
 * a second flag, because the backend writes a pair of columns and not a row in
 * a table it does not have.
 *
 * **It opens nothing.** There is no ticket id in the answer to render, and the
 * surface must not invent one — the response carries the flag and nothing else.
 */
export function flagMessage(messageId: number, reason: FlagReason): Promise<MessageFlag> {
  return alphaFetch<MessageFlag>(`/messages/${messageId}/flag`, {
    method: "POST",
    body: JSON.stringify({ reason }),
  })
}

/** Clear the flag. Both columns, never one of them. */
export function unflagMessage(messageId: number): Promise<MessageFlag> {
  return alphaFetch<MessageFlag>(`/messages/${messageId}/flag`, { method: "DELETE" })
}

/**
 * Mark one assistant message helpful.
 *
 * No body, because the mark carries no reason — the asymmetry with the flag is
 * the point of it. Idempotent per message: a second call answers with the
 * existing stamp rather than moving it.
 */
export function markHelpful(messageId: number): Promise<MessageHelpful> {
  return alphaFetch<MessageHelpful>(`/messages/${messageId}/helpful`, {
    method: "POST",
  })
}

/** Take the mark back, answering with the cleared stamp. */
export function clearHelpful(messageId: number): Promise<MessageHelpful> {
  return alphaFetch<MessageHelpful>(`/messages/${messageId}/helpful`, {
    method: "DELETE",
  })
}

/**
 * Record the reader's choice on one question card.
 *
 * A list even where the card offers one choice, because `multi_select` is a
 * property of the question rather than of the request — one shape here means a
 * card that gains multi-select later changes nothing on this side.
 *
 * **It starts nothing.** The Turn that asked already ended, so this writes down
 * what was chosen and no more; the reply is the next Turn the reader sends.
 * Idempotent per question: the same choice again answers with the row unchanged,
 * a different one on a question already settled is a `409`.
 */
export function answerQuestion(
  questionId: string,
  selectedOptionIds: string[],
): Promise<ResolvedQuestion> {
  return alphaFetch<ResolvedQuestion>(
    `/questions/${encodeURIComponent(questionId)}/answer`,
    {
      method: "POST",
      body: JSON.stringify({ selected_option_ids: selectedOptionIds }),
    },
  )
}

/**
 * Record that the reader declined to choose.
 *
 * No body, because a skip carries no choice — and it is not a cancellation: the
 * work runs on default assumptions and prints them.
 */
export function skipQuestion(questionId: string): Promise<ResolvedQuestion> {
  return alphaFetch<ResolvedQuestion>(
    `/questions/${encodeURIComponent(questionId)}/skip`,
    { method: "POST" },
  )
}

/** Where the browser's `EventSource` points. Same origin, so cookies travel. */
export function turnStreamUrl(turnId: string): string {
  return `${BASE}/turns/${encodeURIComponent(turnId)}/events`
}

/**
 * A fresh Turn id.
 *
 * `crypto.randomUUID` needs a secure context, which localhost and https both
 * are; the fallback exists for the one place that is neither, and it only has
 * to be unique per user rather than unguessable — the backend scopes the id to
 * its owner, so a collision with a stranger's Turn is not reachable.
 */
export function newTurnId(): string {
  if (typeof globalThis.crypto?.randomUUID === "function") {
    return globalThis.crypto.randomUUID()
  }
  return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, (char) => {
    const random = (Math.random() * 16) | 0
    const value = char === "x" ? random : (random & 0x3) | 0x8
    return value.toString(16)
  })
}

/**
 * This account's allowance and what has gone against it.
 *
 * Takes no parameters on purpose: the user is resolved from the session
 * upstream, so there is no shape of this call that reads another account.
 *
 * The numbers move as Turns run, and the daily figures stop being true at
 * Vietnamese midnight — so the caller refetches rather than caching this for
 * the life of the tab.
 */
export function fetchUsage(): Promise<Usage> {
  return alphaFetch<Usage>("/usage")
}

/**
 * What the configured route can do.
 *
 * Separate from {@link fetchUsage} because the two change on different clocks:
 * usage moves with every Turn, and this moves only when the deployment is
 * reconfigured. One endpoint for both would make the constant half be polled at
 * the moving half's rate.
 */
export function fetchCapabilities(): Promise<Capabilities> {
  return alphaFetch<Capabilities>("/capabilities")
}
