/**
 * The Alpha Desk conversation, over the same-origin proxy.
 *
 * Same-origin against the Next route handler rather than FastAPI directly,
 * because the session lives in httpOnly cookies the browser cannot read. That
 * is also why this does not reuse `fetchApi` from `@/lib/api`: those routes are
 * public market data on the API's own origin, and these carry a user.
 *
 * `fetchApi` stays unchanged, deliberately — retro-fitting auth onto the app's
 * twenty-five existing hooks is its own effort (ADR-0013).
 *
 * **Admission outcomes arrive here, not in the stream.** A `429` or a `503`
 * from the create call is an ordinary HTTP failure carrying its stable reason,
 * and the caller reads it from the thrown refusal rather than waiting for an
 * event that is never coming.
 */

import { AlphaRefusalError } from "@/lib/alpha"

import type { CreatedTurn, Thread, ThreadDetail, Turn } from "./types"

const BASE = "/api/alpha-desk"

async function refusalFrom(response: Response): Promise<AlphaRefusalError> {
  try {
    const body = await response.json()
    const detail = body?.detail
    if (detail && typeof detail === "object" && typeof detail.message === "string") {
      return new AlphaRefusalError(response.status, detail.reason ?? null, detail.message)
    }
    if (typeof detail === "string" && detail) {
      return new AlphaRefusalError(response.status, null, detail)
    }
  } catch {
    // Not JSON — a proxy error or an outage. Fall through to the status line.
  }
  return new AlphaRefusalError(
    response.status,
    null,
    `Alpha Desk error: ${response.statusText || response.status}`,
  )
}

async function call<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await fetch(`${BASE}${path}`, {
    ...init,
    headers: { "Content-Type": "application/json", ...init?.headers },
    credentials: "same-origin",
  })
  if (!response.ok) throw await refusalFrom(response)
  if (response.status === 204) return undefined as T
  return (await response.json()) as T
}

/** Open a Thread. Free-roaming: it is not opened against a symbol. */
export function createThread(title?: string | null): Promise<Thread> {
  return call<Thread>("/threads", {
    method: "POST",
    body: JSON.stringify({ title: title ?? null }),
  })
}

/** This user's Threads, most recently touched first. Secondary retrieval only. */
export function listThreads(): Promise<{ threads: Thread[] }> {
  return call<{ threads: Thread[] }>("/threads")
}

/** One Thread and its canonical transcript. */
export function fetchThread(threadId: string): Promise<ThreadDetail> {
  return call<ThreadDetail>(`/threads/${encodeURIComponent(threadId)}`)
}

export interface CreateTurnInput {
  threadId: string
  /** Chosen by the browser before the request. It is the idempotency key. */
  turnId: string
  text: string
  symbols?: string[]
  activeSymbol?: string | null
  retryOfTurnId?: string | null
}

/**
 * Admit and create a Turn.
 *
 * The id is generated by the caller and sent, rather than assigned by the
 * server and returned. That is what makes a retried admission safe on a flaky
 * network: the same id with the same payload resolves to the Turn that already
 * exists instead of starting a second one.
 */
export function createTurn(input: CreateTurnInput): Promise<CreatedTurn> {
  return call<CreatedTurn>(`/threads/${encodeURIComponent(input.threadId)}/turns`, {
    method: "POST",
    body: JSON.stringify({
      turn_id: input.turnId,
      text: input.text,
      symbols: input.symbols ?? [],
      active_symbol: input.activeSymbol ?? null,
      retry_of_turn_id: input.retryOfTurnId ?? null,
    }),
  })
}

/** Idempotent. A second cancel returns the same answer and dispatches nothing. */
export function cancelTurn(turnId: string): Promise<Turn> {
  return call<Turn>(`/turns/${encodeURIComponent(turnId)}/cancel`, { method: "POST" })
}

/** One Turn's current state, for a caller that has not opened a stream. */
export function fetchTurn(turnId: string): Promise<Turn> {
  return call<Turn>(`/turns/${encodeURIComponent(turnId)}`)
}

/** Where the browser's `EventSource` points. Same origin, so cookies travel. */
export function turnStreamUrl(turnId: string): string {
  return `${BASE}/turns/${encodeURIComponent(turnId)}/events`
}

/**
 * A fresh Turn id.
 *
 * `crypto.randomUUID` needs a secure context, which localhost and https both
 * are; the fallback exists for the one place that is neither, and it only has
 * to be unique per user rather than unguessable — the backend scopes the id to
 * its owner, so a collision with a stranger's Turn is not reachable.
 */
export function newTurnId(): string {
  if (typeof globalThis.crypto?.randomUUID === "function") {
    return globalThis.crypto.randomUUID()
  }
  return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, (char) => {
    const random = (Math.random() * 16) | 0
    const value = char === "x" ? random : (random & 0x3) | 0x8
    return value.toString(16)
  })
}
