"""Signals computed from stored sessions, and the provenance they carry.

Nothing in here reaches a Provider Source. A signal is arithmetic over what the
Collector and the Warm-up already wrote, so an evening the provider is down
still answers — with an older session, and saying so.
"""

from .bars import (
    ADTV_MIN_PEERS,
    ADTV_SESSIONS,
    AdjustmentReport,
    Bar,
    BarFrame,
    WindowBandRegime,
    WindowHealth,
    prepare_bars,
)
from .corporate_actions import (
    ActionKind,
    ActionTerms,
    Confirmation,
    ConfirmationReason,
    ConfirmationVerdict,
    CorporateActionStore,
    FactorReading,
    adjustment_factor,
    blend,
    classify,
    confirm_ex_date,
    terms_of,
)
from .issues import SignalIssue
from .price_band import (
    BAND_LIMIT_BY_EXCHANGE,
    EXCHANGE_MIGRATIONS,
    MIGRATION_PROGRAMME_END,
    BandAnchorBasis,
    BandLimits,
    BandReading,
    BandRegime,
    BandRegimeResolver,
    ExchangeAsOf,
    ExchangeMigration,
    LimitLock,
    band_limits,
    detect_limit_lock,
    measure_band,
    resolve_band_regime,
    tick_size,
)
from .sessions import sessions_in_range, sessions_on_days
from .volume_spike import (
    BASELINE_TRADING_DAYS,
    CoverageState,
    Freshness,
    SignalScope,
    VolumeSpikeSignal,
    signal_cache_key,
    volume_spike_signal,
)

__all__ = [
    "ADTV_MIN_PEERS",
    "ADTV_SESSIONS",
    "BAND_LIMIT_BY_EXCHANGE",
    "BASELINE_TRADING_DAYS",
    "ActionKind",
    "ActionTerms",
    "AdjustmentReport",
    "Bar",
    "BarFrame",
    "BandAnchorBasis",
    "BandLimits",
    "BandReading",
    "BandRegime",
    "BandRegimeResolver",
    "Confirmation",
    "ConfirmationReason",
    "ConfirmationVerdict",
    "CorporateActionStore",
    "CoverageState",
    "EXCHANGE_MIGRATIONS",
    "ExchangeAsOf",
    "ExchangeMigration",
    "FactorReading",
    "Freshness",
    "LimitLock",
    "MIGRATION_PROGRAMME_END",
    "SignalIssue",
    "SignalScope",
    "VolumeSpikeSignal",
    "WindowBandRegime",
    "WindowHealth",
    "adjustment_factor",
    "band_limits",
    "blend",
    "classify",
    "confirm_ex_date",
    "detect_limit_lock",
    "measure_band",
    "prepare_bars",
    "resolve_band_regime",
    "sessions_in_range",
    "sessions_on_days",
    "signal_cache_key",
    "terms_of",
    "tick_size",
    "volume_spike_signal",
]
