// @vitest-environment jsdom
/**
 * The panel, against the artifact the server actually sends.
 *
 * The fixture is a real Study run regenerated by `make contracts`, so what is
 * rendered here is the payload the wire carries rather than a sample written to
 * suit the components. Three claims are worth a test:
 *
 * *The skeleton is the right height before anything arrives.* The announcement
 * says how many blocks there are, and a panel that opened empty and then jumped
 * would be worse than one that opened slowly.
 *
 * *A re-opened Thread shows the day the answer was written about.* `asOf` is
 * frozen when the Study runs, and a picture with no date on it reads as now.
 *
 * *A block nothing can draw is still a block.* It degrades to a table and says
 * so, in place, because a dropped block is a hole the reader cannot see.
 */

import { QueryClient, QueryClientProvider } from "@tanstack/react-query"
import { cleanup, render, screen, waitFor } from "@testing-library/react"
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest"

import fixture from "../../../../../contracts/fixtures/artifact-intraday-liquidity.json"
import type { ArtifactPayload } from "@/lib/alpha-desk/types"

const fetchArtifact = vi.fn()
vi.mock("@/lib/alpha-desk/api", () => ({
  fetchArtifact: (id: string) => fetchArtifact(id),
}))

const { CanvasPanel } = await import("./canvas-panel")

const ARTIFACT_ID = "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"

function payload(overrides: Partial<ArtifactPayload> = {}): ArtifactPayload {
  return {
    id: ARTIFACT_ID,
    study_name: fixture.studyName,
    study_version: fixture.studyVersion,
    params: fixture.params,
    canvas_spec: fixture.canvasSpec,
    frames: fixture.frames,
    provenance: fixture.provenance,
    created_at: "2026-08-21T09:00:00+00:00",
    ...overrides,
  } as ArtifactPayload
}

function draw(node: React.ReactElement) {
  const client = new QueryClient({
    defaultOptions: { queries: { retry: false, gcTime: Infinity } },
  })
  return render(<QueryClientProvider client={client}>{node}</QueryClientProvider>)
}

beforeEach(() => {
  fetchArtifact.mockReset()
  // ResizeObserver is what recharts measures its container with, and jsdom has
  // none. A stub that reports nothing is enough: the assertions here are about
  // what is on the page, not about chart geometry.
  vi.stubGlobal(
    "ResizeObserver",
    class {
      observe() {}
      unobserve() {}
      disconnect() {}
    },
  )
})

afterEach(() => {
  cleanup()
  vi.unstubAllGlobals()
})

describe("before the numbers arrive", () => {
  it("holds one skeleton per announced block, so the panel does not jump", () => {
    fetchArtifact.mockReturnValue(new Promise(() => {}))

    const { container } = draw(
      <CanvasPanel artifactId={ARTIFACT_ID} title="Thanh khoản STB" blockCount={4} />,
    )

    expect(container.querySelectorAll(".animate-pulse")).toHaveLength(4)
    expect(screen.getByText("Thanh khoản STB")).toBeInTheDocument()
  })

  it("says so plainly when the conversation has drawn nothing", () => {
    draw(<CanvasPanel artifactId={null} />)

    expect(screen.getByText(/Chưa có phân tích nào/)).toBeInTheDocument()
    expect(fetchArtifact).not.toHaveBeenCalled()
  })
})

describe("once the artifact is fetched", () => {
  it("renders every block of the spec the server sent", async () => {
    fetchArtifact.mockResolvedValue(payload())

    const { container } = draw(<CanvasPanel artifactId={ARTIFACT_ID} blockCount={4} />)

    await waitFor(() =>
      expect(screen.getByText(fixture.canvasSpec.title)).toBeInTheDocument(),
    )
    expect(container.querySelectorAll("section")).toHaveLength(
      fixture.canvasSpec.blocks.length,
    )
    // The heatmap is the hero picture, and it is SVG this build draws itself.
    expect(container.querySelector("svg")).not.toBeNull()
  })

  it("shows the day the numbers were frozen, and how old that is", async () => {
    fetchArtifact.mockResolvedValue(payload())

    draw(<CanvasPanel artifactId={ARTIFACT_ID} />)

    const strip = await screen.findByText(/^vnstock$/)
    const line = strip.parentElement as HTMLElement
    expect(line.textContent).toContain(`${fixture.provenance.sessionsUsed} phiên`)
    // The fixture's as-of is pinned in the past, so the age has to be said.
    expect(line.textContent).toMatch(/ngày trước/)
  })

  it("re-opens on the stored as-of rather than asking for a fresher slice", async () => {
    fetchArtifact.mockResolvedValue(payload())

    const { unmount } = draw(<CanvasPanel artifactId={ARTIFACT_ID} />)
    await screen.findByText(/^vnstock$/)
    unmount()
    draw(<CanvasPanel artifactId={ARTIFACT_ID} />)
    const reopened = await screen.findByText(/^vnstock$/)

    expect(reopened.parentElement?.textContent).toContain(
      `${fixture.provenance.sessionsUsed} phiên`,
    )
    // A second mount is a second query client here, so the fetch happening
    // twice is expected; what must not happen is the *content* moving.
    expect(fetchArtifact).toHaveBeenCalledWith(ARTIFACT_ID)
  })

  it("draws a block it cannot render as a table and says which", async () => {
    fetchArtifact.mockResolvedValue(
      payload({
        canvas_spec: {
          title: "Một khối lạ",
          blocks: [
            {
              widget: "session_heatmap",
              widgetVersion: 99,
              frame: "heatmap",
              options: {},
            },
          ],
        },
      }),
    )

    draw(<CanvasPanel artifactId={ARTIFACT_ID} />)

    expect(await screen.findByText(/Hiển thị dạng bảng/)).toBeInTheDocument()
    expect(screen.getByRole("table")).toBeInTheDocument()
  })

  it("says a canvas could not be opened rather than showing an empty panel", async () => {
    fetchArtifact.mockRejectedValue(new Error("404"))

    draw(<CanvasPanel artifactId={ARTIFACT_ID} />)

    expect(await screen.findByText(/Không mở được phân tích/)).toBeInTheDocument()
  })
})
