"""Evidence contracts, validation, and bounded document extraction."""

from .contracts import (
    ClaimKind,
    ClaimLedger,
    ClaimLink,
    ClaimRef,
    DraftClaim,
    EvidenceKind,
    EvidenceLocation,
    EvidenceRef,
    EvidenceRelation,
    PublicationConfidence,
    PublicationMethod,
    SourceClass,
    TimePrecision,
    TosRisk,
    VerificationVerdict,
    VerifiedClaim,
    VerifierOutcome,
    build_evidence_ref,
)
from .ledger import (
    ClaimLedgerValidationReport,
    LedgerClaimAssessment,
    render_claim_ledger,
    validate_claim_ledger,
)
from .validation import (
    ClaimAssessment,
    ClaimStatus,
    EvidenceValidationReport,
    TextSpan,
    validate_claims,
)

__all__ = (
    "ClaimAssessment",
    "ClaimKind",
    "ClaimLedger",
    "ClaimLedgerValidationReport",
    "ClaimLink",
    "ClaimRef",
    "ClaimStatus",
    "DraftClaim",
    "EvidenceKind",
    "EvidenceLocation",
    "EvidenceRef",
    "EvidenceRelation",
    "EvidenceValidationReport",
    "LedgerClaimAssessment",
    "PublicationConfidence",
    "PublicationMethod",
    "SourceClass",
    "TimePrecision",
    "TosRisk",
    "TextSpan",
    "build_evidence_ref",
    "render_claim_ledger",
    "validate_claim_ledger",
    "validate_claims",
    "VerificationVerdict",
    "VerifiedClaim",
    "VerifierOutcome",
)
