"use client"

/**
 * Every widget, drawn from the real artifact, without a backend running.
 *
 * The fixture is a genuine Study run — `contracts/fixtures/
 * artifact-intraday-liquidity.json`, regenerated by `make contracts` from the
 * server's own compute — so what renders here is the shape the wire actually
 * carries. A handwritten sample would agree with the code until the day the
 * code changed, and then the widgets would be tuned against a payload nobody
 * sends.
 *
 * It exists because look-and-feel is where charts go wrong, and every round
 * trip through *ask a question, wait for a Turn, open the panel* costs a model
 * call to see a border radius. Here the whole panel is one keypress away, in
 * both themes, with a deliberately broken block at the bottom so the degraded
 * path is as visible as the pretty one.
 *
 * Dev only, on the same pattern as `agentation-toolbar.tsx`: gated on
 * `NODE_ENV` so `next build` eliminates the branch, and the fixture JSON is
 * imported through a dynamic component so it never joins a production bundle.
 */

import { useState } from "react"

import fixture from "../../../../../contracts/fixtures/artifact-intraday-liquidity.json"
import { CanvasBlockView } from "../canvas/canvas-block"
import { ProvenanceStrip } from "../canvas/provenance-strip"
import type { CanvasBlock, Frame, Provenance } from "@/lib/alpha-desk/types"

const SPEC = fixture.canvasSpec as unknown as { title: string; blocks: CanvasBlock[] }
const FRAMES = fixture.frames as unknown as Record<string, Frame>
const PROVENANCE = fixture.provenance as unknown as Provenance

/**
 * Blocks nobody sends, so the failures are on screen beside the successes.
 *
 * A widget version this build has never heard of, and a widget asked to draw a
 * frame kind it cannot. Both must degrade to a table with a note rather than
 * throwing — the rule the persisted-version scheme rests on — and a rule only
 * exercised by a unit test is a rule nobody ever *sees* hold.
 */
const DEGRADED: CanvasBlock[] = [
  { widget: "session_heatmap", widgetVersion: 99, frame: "heatmap", options: {} },
  { widget: "bar_series", widgetVersion: 1, frame: "heatmap", options: {} },
]

export function CanvasFixture() {
  const [open, setOpen] = useState(false)
  if (process.env.NODE_ENV === "production") return null

  if (!open) {
    return (
      <button
        type="button"
        onClick={() => setOpen(true)}
        className="fixed bottom-3 left-3 z-50 rounded-full border border-hairline bg-surface-menu px-3 py-1 text-meta text-muted-foreground"
      >
        canvas fixture
      </button>
    )
  }

  return (
    <div className="fixed inset-y-0 right-0 z-50 w-[420px] overflow-y-auto border-l border-border bg-background px-3 py-3 shadow-2xl">
      <div className="flex items-center justify-between">
        <h3 className="text-sm font-medium text-ink-1">{SPEC.title}</h3>
        <button
          type="button"
          onClick={() => setOpen(false)}
          className="text-meta text-muted-foreground"
        >
          đóng
        </button>
      </div>

      <ProvenanceStrip provenance={PROVENANCE} />

      <div className="mt-3 space-y-4">
        {[...SPEC.blocks, ...DEGRADED].map((block, index) => (
          <CanvasBlockView
            key={`${block.widget}-${block.widgetVersion}-${index}`}
            block={block}
            frame={FRAMES[block.frame]}
            provenance={PROVENANCE}
          />
        ))}
      </div>
    </div>
  )
}
