"""add corporate actions

The durable Corporate Action series read-time price adjustment is computed from
(``docs/adr/0006``). Empty until the slow collector runs, and a prerequisite
rather than a refinement: without it every raw-era window containing an ex-date
is refused.

Two partial unique indexes rather than one constraint, because an action with no
ex-date is a real row — the feed leaves it null — and NULLs do not collide under
a plain unique constraint, so those rows are keyed on their public date instead.

Revision ID: 228663431f9c
Revises: d1f4b7c02e93
Create Date: 2026-08-15 13:52:59.308951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '228663431f9c'
down_revision: Union[str, None] = 'd1f4b7c02e93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporate_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=True),
    sa.Column('event_code', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('public_date', sa.Date(), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('exercise_ratio', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('value_per_share', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('changes_share_count', sa.Boolean(), nullable=False),
    sa.Column('confirmation', sa.String(length=16), nullable=False),
    sa.Column('confirmation_reason', sa.String(length=48), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_corporate_action_symbol_ex_date', 'corporate_actions', ['symbol', 'ex_date'], unique=False)
    op.create_index('uq_corporate_action_dated', 'corporate_actions', ['symbol', 'ex_date', 'event_code', 'kind'], unique=True, postgresql_where=sa.text('ex_date IS NOT NULL'), sqlite_where=sa.text('ex_date IS NOT NULL'))
    op.create_index('uq_corporate_action_undated', 'corporate_actions', ['symbol', 'public_date', 'event_code', 'kind'], unique=True, postgresql_where=sa.text('ex_date IS NULL'), sqlite_where=sa.text('ex_date IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_corporate_action_undated', table_name='corporate_actions', postgresql_where=sa.text('ex_date IS NULL'), sqlite_where=sa.text('ex_date IS NULL'))
    op.drop_index('uq_corporate_action_dated', table_name='corporate_actions', postgresql_where=sa.text('ex_date IS NOT NULL'), sqlite_where=sa.text('ex_date IS NOT NULL'))
    op.drop_index('ix_corporate_action_symbol_ex_date', table_name='corporate_actions')
    op.drop_table('corporate_actions')
    # ### end Alembic commands ###
