"""create stock_intraday_bars table

Revision ID: 60811b8fd9e3
Revises: 
Create Date: 2025-12-18 23:24:03.844696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60811b8fd9e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_intraday_bars',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('bar_time', sa.DateTime(), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('high_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('low_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('close_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('trade_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('trade_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'bar_time', name='uq_symbol_bar_time')
    )
    op.create_index('idx_intraday_symbol_date', 'stock_intraday_bars', ['symbol', sa.literal_column('date(bar_time)')], unique=False)
    op.create_index(op.f('ix_stock_intraday_bars_symbol'), 'stock_intraday_bars', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_intraday_bars_symbol'), table_name='stock_intraday_bars')
    op.drop_index('idx_intraday_symbol_date', table_name='stock_intraday_bars')
    op.drop_table('stock_intraday_bars')
    # ### end Alembic commands ###
