"""add the nine Alpha Desk tables

All nine in one revision, even though five of them stay empty until the agent
loop lands (``docs/specs/0003-intelligent-quant-architecture.md`` §10.1). They
come into existence together — ``agent_message`` means nothing without
``agent_thread`` — and nine links on this chain would be nine places to rebase
wrong while buying no partial rollback anyone would take: nobody ships half a
transcript.

The three constraints later milestones rest on are here rather than in
application code: ``analysis`` unique on ``(symbol, trading_day)`` and
deliberately *excluding* ``schema_version``, transcript order held by
``UNIQUE(thread_id, seq)`` rather than by timestamps, and traces anchored by a
NOT NULL ``request_message_id``.

Revision ID: dbd106456567
Revises: 228663431f9c
Create Date: 2026-08-15 15:17:02.129267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dbd106456567'
down_revision: Union[str, None] = '228663431f9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('trading_day', sa.Date(), nullable=False),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'trading_day', name='uq_analysis_symbol_trading_day')
    )
    op.create_index('ix_analysis_symbol_day', 'analysis', ['symbol', sa.literal_column('trading_day DESC')], unique=False)
    op.create_table('analysis_run',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('trading_day', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_code', sa.String(length=48), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'trading_day', name='uq_analysis_run_symbol_trading_day')
    )
    op.create_index('ix_analysis_run_status_started', 'analysis_run', ['status', 'started_at'], unique=False)
    op.create_table('eval_run',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('route', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('tool_catalog_version', sa.String(length=32), nullable=False),
    sa.Column('registry_version', sa.String(length=32), nullable=False),
    sa.Column('fixture_version', sa.String(length=32), nullable=False),
    sa.Column('category_totals', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('report_path', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_call_usage',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('owner_type', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('route', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cached_read_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cache_write_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('output_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reasoning_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('pricing_version', sa.String(length=32), nullable=False),
    sa.Column('input_token_price_usd', sa.Numeric(precision=20, scale=12), nullable=False),
    sa.Column('cached_read_token_price_usd', sa.Numeric(precision=20, scale=12), nullable=False),
    sa.Column('cache_write_token_price_usd', sa.Numeric(precision=20, scale=12), nullable=False),
    sa.Column('output_token_price_usd', sa.Numeric(precision=20, scale=12), nullable=False),
    sa.Column('reserved_micro_usd', sa.BigInteger(), nullable=False),
    sa.Column('actual_micro_usd', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reconciled_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_llm_call_usage_created', 'llm_call_usage', ['created_at'], unique=False)
    op.create_index('ix_llm_call_usage_owner', 'llm_call_usage', ['owner_type', 'owner_id'], unique=False)
    op.create_table('agent_thread',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('symbols', postgresql.ARRAY(sa.String(length=20)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_thread_symbols', 'agent_thread', ['symbols'], unique=False, postgresql_using='gin')
    op.create_index('ix_agent_thread_user_updated', 'agent_thread', ['user_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('watchlist_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_analysis_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'symbol', name='uq_watchlist_entry_user_symbol')
    )
    op.create_index('ix_watchlist_entry_user_added', 'watchlist_entries', ['user_id', 'added_at'], unique=False)
    op.create_table('agent_message',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('thread_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('flagged_reason', sa.String(length=48), nullable=True),
    sa.Column('flagged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['agent_thread.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id', 'seq', name='uq_agent_message_thread_seq')
    )
    op.create_table('agent_tool_call',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('thread_id', sa.Uuid(), nullable=False),
    sa.Column('request_message_id', sa.BigInteger(), nullable=False),
    sa.Column('tool_name', sa.String(length=64), nullable=False),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_message_id'], ['agent_message.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['agent_thread.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_tool_call_request_message', 'agent_tool_call', ['request_message_id'], unique=False)
    op.create_index('ix_agent_tool_call_started', 'agent_tool_call', ['started_at'], unique=False)
    op.create_table('agent_turn',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sa.Uuid(), nullable=False),
    sa.Column('request_message_id', sa.BigInteger(), nullable=False),
    sa.Column('response_message_id', sa.BigInteger(), nullable=True),
    sa.Column('retry_of_turn_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('terminal_reason', sa.String(length=48), nullable=True),
    sa.Column('cancel_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_event_seq', sa.Integer(), server_default='0', nullable=False),
    sa.Column('draft_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['request_message_id'], ['agent_message.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['response_message_id'], ['agent_message.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['retry_of_turn_id'], ['agent_turn.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thread_id'], ['agent_thread.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_turn_thread_started', 'agent_turn', ['thread_id', sa.literal_column('started_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_agent_turn_thread_started', table_name='agent_turn')
    op.drop_table('agent_turn')
    op.drop_index('ix_agent_tool_call_started', table_name='agent_tool_call')
    op.drop_index('ix_agent_tool_call_request_message', table_name='agent_tool_call')
    op.drop_table('agent_tool_call')
    op.drop_table('agent_message')
    op.drop_index('ix_watchlist_entry_user_added', table_name='watchlist_entries')
    op.drop_table('watchlist_entries')
    op.drop_index('ix_agent_thread_user_updated', table_name='agent_thread')
    op.drop_index('ix_agent_thread_symbols', table_name='agent_thread', postgresql_using='gin')
    op.drop_table('agent_thread')
    op.drop_index('ix_llm_call_usage_owner', table_name='llm_call_usage')
    op.drop_index('ix_llm_call_usage_created', table_name='llm_call_usage')
    op.drop_table('llm_call_usage')
    op.drop_table('eval_run')
    op.drop_index('ix_analysis_run_status_started', table_name='analysis_run')
    op.drop_table('analysis_run')
    op.drop_index('ix_analysis_symbol_day', table_name='analysis')
    op.drop_table('analysis')
    # ### end Alembic commands ###
