"""store listing industries for agent tools

Revision ID: e35e33d54edf
Revises: a365676b9d01
Create Date: 2026-08-15 22:50:28.743767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'e35e33d54edf'
down_revision: Union[str, None] = 'a365676b9d01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing_roster', sa.Column('industry_code', sa.String(length=20), nullable=True))
    op.add_column('listing_roster', sa.Column('industry_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listing_roster', 'industry_name')
    op.drop_column('listing_roster', 'industry_code')
    # ### end Alembic commands ###
